#:schema node_modules/wrangler/config-schema.json
name = "sublink-work"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "6737913b243249a4ad61acf9f9b93c00" }
]

[assets]
directory = "./public"
